# Generated by Django 4.2 on 2026-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('TOOLS', 'Tools & DevOps'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class (e.g. fa-brands fa-python)', max_length=50)),
            ],
        ),
    ]
