# Generated by Django 4.2 on 2026-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
    ]
